Repository GEOS-ESM/GEOSldas_GridComp, pull requests merged in 2024-04, with the labels that each got.

#17 fix slurm entry to match remap_params.tpl
  CHANGELOG.md
  GEOSldas_App/ldas_setup
Labels: 0-diff, bug fix

#20 merge develop into BRIDGE in prep for release v1.0.1
  CHANGELOG.md
  GEOSldas_App/ldas_setup
Labels: 0-diff, bug fix

#23 merge BRIDGE into main in prep for release v1.0.1
  CHANGELOG.md
  GEOSldas_App/ldas_setup
Labels: 0-diff, bug fix

#26 Bugfix for state increment array referencing in update_type=13
  CHANGELOG.md
  GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
Labels: 0-diff, bug fix

#27 Move GEOSgcm_GridComp under Components in GEOSldas
  CHANGELOG.md
  CMakeLists.txt
Labels: 0-diff

#30 Update .gitignore to remove GEOSgcm_GridComp references
  .gitignore
Labels: Skip Changelog, 0-diff trivial

#16 cleanup lenkf.j.template
  CHANGELOG.md
  GEOSldas_App/CMakeLists.txt
  GEOSldas_App/ldas_setup
  GEOSldas_App/lenkf_j_template.py
Labels: 0-diff

#32 merge develop into BRIDGE in preparation for release v1.0.2
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  GEOSldas_App/CMakeLists.txt
  GEOSldas_App/ldas_setup
  GEOSldas_App/lenkf_j_template.py
Labels: 0-diff, bug fix

#36 Update CHANGELOG.md in preparation for release v1.0.2
  CHANGELOG.md
Labels: documentation, 0-diff trivial

#37 merge develop into BRIDGE in prep for release v1.0.2 (again, after additional changes on develop)
  .circleci/config.yml
  CHANGELOG.md
Labels: 0-diff

#38 Merge develop into main in prep for release v1.0.2
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  GEOSlandassim_GridComp/clsm_ensupd_upd_routines.F90
  GEOSldas_App/CMakeLists.txt
  GEOSldas_App/ldas_setup
  GEOSldas_App/lenkf_j_template.py
Labels: 0-diff
