Repository GEOS-ESM/GEOSldas_GridComp, pull requests merged in 2025-06, with the labels that each got.

#102 revisions for handling of Nens and special nml and mwtrm path/files in coupled land-atm DAS
  CHANGELOG.md
  GEOSldas_App/CMakeLists.txt
  GEOSldas_App/LandAtmDAS_nml/LDASsa_SPECIAL_inputs_ensprop.nml
  GEOSldas_App/LandAtmDAS_nml/LDASsa_SPECIAL_inputs_ensupd.nml
  GEOSldas_App/ldas_setup
Labels: enhancement, 0-diff

#106 Specify only ntasks_model for SLURM resource request
  CHANGELOG.md
  GEOSldas_App/ldas_setup
  GEOSldas_App/lenkf_j_template.py
Labels: infrastructure, 0-diff

#109 added stretch grid items to LDAS.rc
  CHANGELOG.md
  GEOSldas_App/ldas_setup
Labels: 0-diff

#104 Update some defaults in LDASsa_DEFAULT_inputs_*.nml files
  CHANGELOG.md
  GEOSldas_App/LDASsa_DEFAULT_inputs_ensprop.nml
  GEOSldas_App/LDASsa_DEFAULT_inputs_ensupd.nml
Labels: 0-diff trivial

#112 Add optional SLURM "constraint"
  CHANGELOG.md
  GEOSldas_App/ldas_setup
Labels: 0-diff

#115 Switch EASE grid handling to new MAPL EASE Grid Factory
  CHANGELOG.md
  GEOS_LdasGridComp.F90
  GEOSlandassim_GridComp/clsm_ensupd_enkf_update.F90
  GEOSlandassim_GridComp/clsm_ensupd_read_obs.F90
  GEOSldas_App/ldas_setup
  GEOSldas_App/preprocess_ldas_routines.F90
  LDAS_Shared/LDAS_TileCoordRoutines.F90
Labels: infrastructure, 0-diff

#118 Revised processing of HISTORY template (GEOSldas_HIST.rc)
  CHANGELOG.md
  GEOSldas_App/GEOSldas_HIST.rc
  GEOSldas_App/ldas_setup
  GEOSldas_App/process_hist.csh
Labels: 0-diff, pre-processing

#124 Update CHANGELOG.md in prep for release v3.1.0 (re-issued)
  CHANGELOG.md
  GEOS_LdasGridComp.F90
Labels: documentation, 0-diff trivial

#122 Update CHANGELOG.md in prep for release v3.1.0
  CHANGELOG.md
Labels: documentation, 0-diff trivial
